<section class="section">
<div class="container">
	<div class="columns">
        	<div class="column  is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
        	<div class="column is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
        	<div class="column is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
        	<div class="column is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
        	<div class="column is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
        	<div class="column is-2">
        		<figure class="image is-128x128">
        			<img src="http://placehold.it/128x128">
        		</figure>
        	</div>
	</div>
</div>
</section>
