<?php ob_start(); ?>
<header>
<nav class="nav">
<div class="nav-left">
<a class="nav-item is-brand" href="/">
<strong>
	Fourleafclover
</strong>
</a>
</div>


<span class="nav-toggle">
<span></span>
<span></span>
<span></span>
</span>

<div class="nav-right nav-menu">
</a>
<a class="nav-item" href="#">
Shopping cart(0)
</a>
<a class="nav-item" href="#">
Wish list(0)
</a>

<span class="nav-item">
<a class="button is-primary" href="<?= url('/user/login')?>">
<span>login</span>
</a>
</span>
</div>
</nav>

</header>
<?php  $content=ob_get_contents() ?>
<?php  ob_end_clean(); ?>
