<?php ob_start(); ?>
<header>
<nav class="nav">
<div class="nav-left">
<a class="nav-item is-brand" href="/">
	<img src="http://bulma.io/images/bulma-type.png" alt="">
</a>
</div>


<span class="nav-toggle">
<span></span>
<span></span>
<span></span>
</span>

<div class="nav-right nav-menu">
</a>
<a class="nav-item" href="/shop/shopcart">
购物车(0)
</a>
<a class="nav-item" href="/shop/wishlist">
心愿单(0)
</a>

<span class="nav-item">
<a class="button is-primary" href="<?= url('/user/login')?>">
<span>登录</span>
</a>
</span>
</div>
</nav>

</header>
<?php  $content=ob_get_contents() ?>
<?php  ob_end_clean(); ?>
