<nav class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <a class="nav-item is-tab is-active">首页</a>
      <a class="nav-item is-tab">衬衫</a>
      <a class="nav-item is-tab">水柔棉</a>
      <a class="nav-item is-tab">羽绒服</a>
      <a class="nav-item is-tab">外套</a>
      <a class="nav-item is-tab">针织衫</a>
      <a class="nav-item is-tab">裤装</a>
      <a class="nav-item is-tab">鞋</a>
      <a class="nav-item is-tab">袜品</a>
      <a class="nav-item is-tab">家居配饰</a>
    </div>
  </div>
</nav>
