<script src="/bower_components/unslider/dist/js/unslider-min.js"></script>
<link href="/bower_components/unslider/dist/css/unslider.css" rel="stylesheet" type="text/css"  />
<link href="/bower_components/unslider/dist/css/unslider-dots.css" rel="stylesheet" type="text/css"  />
<div class="slider" dir="rtl">
	<ul style="text-align:center;    background-color: rgb(247,247,246)">
		<li style="background-color: rgb(247,247,246)">
			<img src="http://i4.vanclimg.com/cms/20161104/sj.jpg" />
		</li>
	</ul>
</div>
<script>
$(function(){
	$('.slider').unslider({
	nimation: 'fade',
	autoplay: true,
	arrows: false
	});	
})
</script>
