<label class="label">Username:</label>
<p class="control">
  <input class="input" type="text" placeholder="username input" id="username">
</p>
<label class="label">Password:</label>
<p class="control">
  <input class="input" type="password" placeholder="password input" value="" id="password">
</p>
<p class="control">
  <label class="checkbox">
    <input type="checkbox" id="remember">
    Remember me
  </label>
</p>
<p class="control">
  <button class="button is-primary">Login</button>
  <a class="button is-link" href="<?= url('/user/signup') ?>">Signup</a>
</p>
