<label class="label">Email:</label>
<p class="control">
  <input class="input" type="email" placeholder="E-mail" id="email">
</p>
<label class="label">Username:</label>
<p class="control">
  <input class="input" type="text" placeholder="username input" id="username">
</p>
<label class="label">Password:</label>
<p class="control">
  <input class="input" type="password" placeholder="password input" value="" id="password">
</p>
<label class="label">Confirm Password:</label>
<p class="control">
  <input class="input" type="password" placeholder="password input" value="" id="password">
</p>
<p class="control">
  <label class="checkbox">
    <input type="checkbox" id="license">
    license
  </label>
</p>
<p class="control">
  <button class="button is-primary" id="signup">Signup</button>
  <a class="button is-link" href="<?= url('/user/login') ?>">Login</a>
</p>
